In [1]:
import pandas as pd
from google.colab import files
files.upload()

Saving generated_data.csv to generated_data.csv


{'generated_data.csv': b',x,y\r\n0,18.0,5.631\r\n1,33.0,11.016\r\n2,9.0,2.161\r\n3,29.0,9.866000000000001\r\n4,15.0,4.091\r\n5,14.0,4.091\r\n6,17.0,4.856\r\n7,13.0,3.3209999999999997\r\n8,24.0,7.936\r\n9,13.0,3.7060000000000004\r\n10,3.0,-0.529\r\n11,24.0,7.936\r\n12,21.0,6.401000000000001\r\n13,0.0,-1.304\r\n14,27.0,8.711\r\n15,14.0,3.7060000000000004\r\n16,5.0,0.241\r\n17,9.0,1.7809999999999997\r\n18,6.0,1.0060000000000002\r\n19,24.0,7.936\r\n20,22.0,7.171\r\n21,21.0,6.396000000000001\r\n22,26.0,8.321\r\n23,28.0,9.091000000000001\r\n24,29.0,9.866000000000001\r\n25,3.0,-0.14900000000000002\r\n26,8.0,1.7809999999999997\r\n27,29.0,9.481000000000002\r\n28,18.0,5.631\r\n29,7.0,1.0110000000000001\r\n30,9.0,2.166\r\n31,25.0,7.936\r\n32,19.0,5.626\r\n33,23.0,7.556\r\n34,17.0,5.241\r\n35,0.0,-1.2990000000000002\r\n36,20.0,6.396000000000001\r\n37,2.0,-0.919\r\n38,1.0,-1.304\r\n39,22.0,7.166\r\n40,21.0,6.7860000000000005\r\n41,28.0,9.481000000000002\r\n42,15.0,4.476\r\n43,20.0,6.016\r\n44,26.0,

In [2]:
df = pd.read_csv("generated_data.csv")
df.dtypes

Unnamed: 0      int64
x             float64
y             float64
dtype: object

In [47]:
x = df["x"].values.reshape(100,1).tolist()
y = df["y"].values.reshape(100,1).tolist()

In [48]:
x

[[18.0],
 [33.0],
 [9.0],
 [29.0],
 [15.0],
 [14.0],
 [17.0],
 [13.0],
 [24.0],
 [13.0],
 [3.0],
 [24.0],
 [21.0],
 [0.0],
 [27.0],
 [14.0],
 [5.0],
 [9.0],
 [6.0],
 [24.0],
 [22.0],
 [21.0],
 [26.0],
 [28.0],
 [29.0],
 [3.0],
 [8.0],
 [29.0],
 [18.0],
 [7.0],
 [9.0],
 [25.0],
 [19.0],
 [23.0],
 [17.0],
 [0.0],
 [20.0],
 [2.0],
 [1.0],
 [22.0],
 [21.0],
 [28.0],
 [15.0],
 [20.0],
 [26.0],
 [32.0],
 [22.0],
 [12.0],
 [15.0],
 [2.0],
 [25.0],
 [23.0],
 [22.0],
 [31.0],
 [31.0],
 [4.0],
 [6.0],
 [22.0],
 [5.0],
 [32.0],
 [7.0],
 [34.0],
 [5.0],
 [28.0],
 [32.0],
 [22.0],
 [30.0],
 [12.0],
 [14.0],
 [2.0],
 [18.0],
 [34.0],
 [11.0],
 [28.0],
 [9.0],
 [25.0],
 [1.0],
 [34.0],
 [33.0],
 [2.0],
 [3.0],
 [29.0],
 [24.0],
 [27.0],
 [30.0],
 [2.0],
 [14.0],
 [19.0],
 [32.0],
 [20.0],
 [34.0],
 [7.0],
 [18.0],
 [3.0],
 [25.0],
 [23.0],
 [13.0],
 [16.0],
 [2.0],
 [20.0]]

In [49]:
y

[[5.631],
 [11.015999999999998],
 [2.161],
 [9.866],
 [4.091],
 [4.091],
 [4.856],
 [3.321],
 [7.936],
 [3.706],
 [-0.529],
 [7.936],
 [6.401000000000002],
 [-1.304],
 [8.711],
 [3.706],
 [0.24100000000000002],
 [1.7809999999999997],
 [1.0060000000000002],
 [7.936],
 [7.171],
 [6.396000000000001],
 [8.321],
 [9.091],
 [9.866],
 [-0.14900000000000002],
 [1.7809999999999997],
 [9.481000000000002],
 [5.631],
 [1.011],
 [2.166],
 [7.936],
 [5.626],
 [7.556],
 [5.2410000000000005],
 [-1.2990000000000002],
 [6.396000000000001],
 [-0.919],
 [-1.304],
 [7.166],
 [6.7860000000000005],
 [9.481000000000002],
 [4.476],
 [6.016],
 [8.326],
 [10.630999999999998],
 [6.7810000000000015],
 [2.931],
 [4.086],
 [-0.919],
 [8.321],
 [7.166],
 [6.7810000000000015],
 [10.630999999999998],
 [10.630999999999998],
 [-0.14900000000000002],
 [0.626],
 [6.7810000000000015],
 [0.621],
 [10.636],
 [1.011],
 [11.790999999999999],
 [0.23600000000000002],
 [9.476],
 [10.630999999999998],
 [6.7810000000000015],
 [10.25

In [7]:
import tensorflow as tf

In [50]:
X = tf.constant(x)

In [51]:
y = tf.constant(y)

In [52]:
X

<tf.Tensor: shape=(100, 1), dtype=float32, numpy=
array([[18.],
       [33.],
       [ 9.],
       [29.],
       [15.],
       [14.],
       [17.],
       [13.],
       [24.],
       [13.],
       [ 3.],
       [24.],
       [21.],
       [ 0.],
       [27.],
       [14.],
       [ 5.],
       [ 9.],
       [ 6.],
       [24.],
       [22.],
       [21.],
       [26.],
       [28.],
       [29.],
       [ 3.],
       [ 8.],
       [29.],
       [18.],
       [ 7.],
       [ 9.],
       [25.],
       [19.],
       [23.],
       [17.],
       [ 0.],
       [20.],
       [ 2.],
       [ 1.],
       [22.],
       [21.],
       [28.],
       [15.],
       [20.],
       [26.],
       [32.],
       [22.],
       [12.],
       [15.],
       [ 2.],
       [25.],
       [23.],
       [22.],
       [31.],
       [31.],
       [ 4.],
       [ 6.],
       [22.],
       [ 5.],
       [32.],
       [ 7.],
       [34.],
       [ 5.],
       [28.],
       [32.],
       [22.],
       [30.],
       [12.]

In [53]:
y

<tf.Tensor: shape=(100, 1), dtype=float32, numpy=
array([[ 5.631],
       [11.016],
       [ 2.161],
       [ 9.866],
       [ 4.091],
       [ 4.091],
       [ 4.856],
       [ 3.321],
       [ 7.936],
       [ 3.706],
       [-0.529],
       [ 7.936],
       [ 6.401],
       [-1.304],
       [ 8.711],
       [ 3.706],
       [ 0.241],
       [ 1.781],
       [ 1.006],
       [ 7.936],
       [ 7.171],
       [ 6.396],
       [ 8.321],
       [ 9.091],
       [ 9.866],
       [-0.149],
       [ 1.781],
       [ 9.481],
       [ 5.631],
       [ 1.011],
       [ 2.166],
       [ 7.936],
       [ 5.626],
       [ 7.556],
       [ 5.241],
       [-1.299],
       [ 6.396],
       [-0.919],
       [-1.304],
       [ 7.166],
       [ 6.786],
       [ 9.481],
       [ 4.476],
       [ 6.016],
       [ 8.326],
       [10.631],
       [ 6.781],
       [ 2.931],
       [ 4.086],
       [-0.919],
       [ 8.321],
       [ 7.166],
       [ 6.781],
       [10.631],
       [10.631],
       [-0.149]

In [54]:
class Linear(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.dense = tf.keras.layers.Dense(
          units=1,
          activation=None,
          kernel_initializer=tf.zeros_initializer(),
          bias_initializer=tf.zeros_initializer()
        )
    def call(self, input):
        output = self.dense(input)
        return output

In [58]:
model = Linear()
optimizer = tf.keras.optimizers.SGD(learning_rate=0.00001)

In [60]:
for i in range(100000):
    with tf.GradientTape() as tape:
        y_pred = model(X)
        loss = tf.reduce_mean(tf.square(y_pred - y))  
    grads = tape.gradient(loss, model.variables)

    optimizer.apply_gradients(grads_and_vars=zip(grads, model.variables))
print(model.variables)

[<tf.Variable 'linear_6/dense_6/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[0.3746927]], dtype=float32)>, <tf.Variable 'linear_6/dense_6/bias:0' shape=(1,) dtype=float32, numpy=array([-1.2585688], dtype=float32)>]
